<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wML"
    nsURI="http://www.wesnoth.org/WML" nsPrefix="wML">
  <eClassifiers xsi:type="ecore:EClass" name="WMLRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//WMLTag"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="macroCalls" upperBound="-1"
        eType="#//WMLAbstractMacroCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WMLTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//WMLTag"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//WMLKey"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="macroCalls" upperBound="-1"
        eType="#//WMLAbstractMacroCall" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WMLKey">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//WMLAbstractKeyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extraArgs" upperBound="-1"
        eType="#//WMLAbstractKeyValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WMLAbstractMacroCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="WMLMacroInclude" eSuperTypes="#//WMLAbstractMacroCall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WMLMacroCall" eSuperTypes="#//WMLAbstractMacroCall #//WMLAbstractKeyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//WMLAbstractKeyValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WMLAbstractKeyValue"/>
</ecore:EPackage>
