<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wML"
    nsURI="http://www.wesnoth.org/WML" nsPrefix="wML">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textdomains" upperBound="-1"
        eType="#//TextDomain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preproc" upperBound="-1"
        eType="#//Preprocessor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roots" upperBound="-1"
        eType="#//RootType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextDomain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DomainName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preprocessor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Macro" eSuperTypes="#//Preprocessor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="macroContent" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathInclude" eSuperTypes="#//Preprocessor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="startTag" eType="#//RootTag"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1"
        eType="#//RootType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="at" upperBound="-1" eType="#//Attributes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="okpreproc" upperBound="-1"
        eType="#//Preprocessor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endTag" eType="#//RootTag"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleTag" eSuperTypes="#//RootTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddedTag" eSuperTypes="#//RootTag"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
