<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wML"
    nsURI="http://www.wesnoth.org/WML" nsPrefix="wML">
  <eClassifiers xsi:type="ecore:EClass" name="WMLRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Rtags" upperBound="-1"
        eType="#//WMLTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Rmacros" upperBound="-1"
        eType="#//WMLMacro" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WMLMacro">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagcontent" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WMLTag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//WMLStartTag"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Ttags" upperBound="-1"
        eType="#//WMLTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tkeys" upperBound="-1"
        eType="#//WMLKey" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tmacros" upperBound="-1"
        eType="#//WMLMacro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//WMLEndTag"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WMLStartTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WMLEndTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WMLKey">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
