#!/bin/bash -xe

REPO=`pwd`/../..

rm -rf /tmp/wesnoth-aab-base

for arch in "x86_64" "armeabi-v7a" "arm64-v8a" "x86"
do
	mkdir -p /tmp/wesnoth-$arch
	pushd /tmp/wesnoth-$arch
		scons -j`nproc` -Y $REPO prefix=/tmp/android-prefix/$arch host=android-$arch ndkdir=/opt/android-sdk-update-manager/ndk/23.1.7779620 android_home=/opt/android-sdk-update-manager/ apk
	popd
	mkdir -p /tmp/wesnoth-aab-base
	pushd /tmp/wesnoth-aab-base
		unzip -n /tmp/wesnoth-$arch/packaging/android/wesnoth-debug.apk
	popd
done
pushd /tmp/wesnoth-aab-base
	mkdir manifest
	mv AndroidManifest.xml manifest/
	mkdir dex
	mv classes.dex dex/
	zip -r base.zip *
popd
wget -nc https://github.com/google/bundletool/releases/download/1.16.0/bundletool-all-1.16.0.jar
BUNDLETOOL=bundletool-all-1.16.0.jar
rm wesnoth-debug.aab
java -jar $BUNDLETOOL build-bundle --modules=/tmp/wesnoth-aab-base/base.zip --output=wesnoth-debug.aab
rm wesnoth-debug.apks
java -jar $BUNDLETOOL build-apks --bundle=wesnoth-debug.aab --output=wesnoth-debug.apks
