#!/bin/bash -xe

REPO=`pwd`/../..
ANDROID_HOME=/opt/android-sdk-update-manager/
NDKDIR=$ANDROID_HOME/ndk/23.1.7779620
BUILDDIR_PREFIX=/tmp

for arch in "x86_64" "armeabi-v7a" "arm64-v8a" "x86"
do
	mkdir -p $BUILDDIR_PREFIX/wesnoth-$arch
	pushd $BUILDDIR_PREFIX/wesnoth-$arch
		scons -j`nproc` -Y $REPO prefix=$BUILDDIR_PREFIX/android-prefix/$arch host=android-$arch ndkdir=$NDKDIR extra_flags_config=-lm autorevision=false android_api=23 android_home=$ANDROID_HOME native-lib
	popd

	LIBDIR=$REPO/packaging/android/app/src/main/jniLibs/$arch

	mkdir -p $LIBDIR
	rm -f $LIBDIR/*.so
	cp -v $BUILDDIR_PREFIX/android-prefix/$arch/lib/*.so $LIBDIR/
	cp -v $BUILDDIR_PREFIX/wesnoth-$arch/packaging/android/lib/libmain.so $LIBDIR/

	# rename libSDL2-2.0.so -> libSDL2.so, otherwise the final apk(s) won't be able to find it
	mv -v $LIBDIR/libSDL2-2.0.so $LIBDIR/libSDL2.so
done
