set(VCPKG_ENV_PASSTHROUGH_UNTRACKED EMSCRIPTEN_ROOT EMSDK PATH)

if(NOT DEFINED ENV{EMSCRIPTEN_ROOT})
   find_path(EMSCRIPTEN_ROOT "emcc")
else()
   set(EMSCRIPTEN_ROOT "$ENV{EMSCRIPTEN_ROOT}")
endif()

if(NOT EMSCRIPTEN_ROOT)
   if(NOT DEFINED ENV{EMSDK})
      message(FATAL_ERROR "The emcc compiler not found in PATH")
   endif()
   set(EMSCRIPTEN_ROOT "$ENV{EMSDK}/upstream/emscripten")
endif()

if(NOT EXISTS "${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake")
   message(FATAL_ERROR "Emscripten.cmake toolchain file not found")
endif()

set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Emscripten)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake")

# Force atomics-capable objects/libraries for SharedArrayBuffer pthread builds.
set(_WESNOTH_PTHREAD_FLAG "-pthread -matomics -mbulk-memory")
set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} ${_WESNOTH_PTHREAD_FLAG}")
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} ${_WESNOTH_PTHREAD_FLAG}")
set(VCPKG_LINKER_FLAGS "${VCPKG_LINKER_FLAGS} ${_WESNOTH_PTHREAD_FLAG}")
set(VCPKG_C_FLAGS_DEBUG "${VCPKG_C_FLAGS_DEBUG} ${_WESNOTH_PTHREAD_FLAG}")
set(VCPKG_CXX_FLAGS_DEBUG "${VCPKG_CXX_FLAGS_DEBUG} ${_WESNOTH_PTHREAD_FLAG}")
set(VCPKG_LINKER_FLAGS_DEBUG "${VCPKG_LINKER_FLAGS_DEBUG} ${_WESNOTH_PTHREAD_FLAG}")
set(VCPKG_C_FLAGS_RELEASE "${VCPKG_C_FLAGS_RELEASE} ${_WESNOTH_PTHREAD_FLAG}")
set(VCPKG_CXX_FLAGS_RELEASE "${VCPKG_CXX_FLAGS_RELEASE} ${_WESNOTH_PTHREAD_FLAG}")
set(VCPKG_LINKER_FLAGS_RELEASE "${VCPKG_LINKER_FLAGS_RELEASE} ${_WESNOTH_PTHREAD_FLAG}")

# Some CMake-based ports (notably sdl2-image) don't automatically consume
# VCPKG_C_FLAGS/VCPKG_CXX_FLAGS, so force these through configure options too.
set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    "${VCPKG_CMAKE_CONFIGURE_OPTIONS} "
    "-DCMAKE_C_FLAGS=${_WESNOTH_PTHREAD_FLAG} "
    "-DCMAKE_CXX_FLAGS=${_WESNOTH_PTHREAD_FLAG} "
    "-DCMAKE_EXE_LINKER_FLAGS=${_WESNOTH_PTHREAD_FLAG} "
    "-DCMAKE_SHARED_LINKER_FLAGS=${_WESNOTH_PTHREAD_FLAG} "
    "-DCMAKE_MODULE_LINKER_FLAGS=${_WESNOTH_PTHREAD_FLAG}")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS_DEBUG
    "${VCPKG_CMAKE_CONFIGURE_OPTIONS_DEBUG} "
    "-DCMAKE_C_FLAGS_DEBUG=${_WESNOTH_PTHREAD_FLAG} "
    "-DCMAKE_CXX_FLAGS_DEBUG=${_WESNOTH_PTHREAD_FLAG}")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS_RELEASE
    "${VCPKG_CMAKE_CONFIGURE_OPTIONS_RELEASE} "
    "-DCMAKE_C_FLAGS_RELEASE=${_WESNOTH_PTHREAD_FLAG} "
    "-DCMAKE_CXX_FLAGS_RELEASE=${_WESNOTH_PTHREAD_FLAG}")
