set(VCPKG_ENV_PASSTHROUGH_UNTRACKED EMSCRIPTEN_ROOT EMSDK PATH)

if(NOT DEFINED ENV{EMSCRIPTEN_ROOT})
   find_path(EMSCRIPTEN_ROOT "emcc")
else()
   set(EMSCRIPTEN_ROOT "$ENV{EMSCRIPTEN_ROOT}")
endif()

if(NOT EMSCRIPTEN_ROOT)
   if(NOT DEFINED ENV{EMSDK})
      message(FATAL_ERROR "The emcc compiler not found in PATH")
   endif()
   set(EMSCRIPTEN_ROOT "$ENV{EMSDK}/upstream/emscripten")
endif()

if(NOT EXISTS "${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake")
   message(FATAL_ERROR "Emscripten.cmake toolchain file not found")
endif()

set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Emscripten)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake")

# Use native WASM exception handling instead of JS-based invoke_* trampolines.
# Required for JSPI: JSPI can only suspend through pure WASM frames, and
# JS-based exceptions (invoke_*) create JS frames that block suspension.
set(_WESNOTH_WASM_EH_FLAG "-fwasm-exceptions")
set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} ${_WESNOTH_WASM_EH_FLAG}")
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} ${_WESNOTH_WASM_EH_FLAG}")
set(VCPKG_LINKER_FLAGS "${VCPKG_LINKER_FLAGS} ${_WESNOTH_WASM_EH_FLAG}")
set(VCPKG_C_FLAGS_DEBUG "${VCPKG_C_FLAGS_DEBUG} ${_WESNOTH_WASM_EH_FLAG}")
set(VCPKG_CXX_FLAGS_DEBUG "${VCPKG_CXX_FLAGS_DEBUG} ${_WESNOTH_WASM_EH_FLAG}")
set(VCPKG_LINKER_FLAGS_DEBUG "${VCPKG_LINKER_FLAGS_DEBUG} ${_WESNOTH_WASM_EH_FLAG}")
set(VCPKG_C_FLAGS_RELEASE "${VCPKG_C_FLAGS_RELEASE} ${_WESNOTH_WASM_EH_FLAG}")
set(VCPKG_CXX_FLAGS_RELEASE "${VCPKG_CXX_FLAGS_RELEASE} ${_WESNOTH_WASM_EH_FLAG}")
set(VCPKG_LINKER_FLAGS_RELEASE "${VCPKG_LINKER_FLAGS_RELEASE} ${_WESNOTH_WASM_EH_FLAG}")

# Meson-based ports (cairo, pango, harfbuzz, fribidi, glib) read compiler flags
# from VCPKG_COMBINED_C_FLAGS which is built from CMAKE_C_FLAGS, not VCPKG_C_FLAGS.
# Inject via VCPKG_CMAKE_CONFIGURE_OPTIONS so the flag flows through cmake-get-vars
# into meson cross-files.
set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    "${VCPKG_CMAKE_CONFIGURE_OPTIONS} "
    "-DCMAKE_C_FLAGS=${_WESNOTH_WASM_EH_FLAG} "
    "-DCMAKE_CXX_FLAGS=${_WESNOTH_WASM_EH_FLAG} "
    "-DCMAKE_EXE_LINKER_FLAGS=${_WESNOTH_WASM_EH_FLAG} "
    "-DCMAKE_SHARED_LINKER_FLAGS=${_WESNOTH_WASM_EH_FLAG} "
    "-DCMAKE_MODULE_LINKER_FLAGS=${_WESNOTH_WASM_EH_FLAG}")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS_DEBUG
    "${VCPKG_CMAKE_CONFIGURE_OPTIONS_DEBUG} "
    "-DCMAKE_C_FLAGS_DEBUG=${_WESNOTH_WASM_EH_FLAG} "
    "-DCMAKE_CXX_FLAGS_DEBUG=${_WESNOTH_WASM_EH_FLAG}")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS_RELEASE
    "${VCPKG_CMAKE_CONFIGURE_OPTIONS_RELEASE} "
    "-DCMAKE_C_FLAGS_RELEASE=${_WESNOTH_WASM_EH_FLAG} "
    "-DCMAKE_CXX_FLAGS_RELEASE=${_WESNOTH_WASM_EH_FLAG}")
