# vi: syntax=python:et:ts=4
from os.path import join
Import("env")

env["IM_CONVERT"] = '"' + WhereIs("convert") + '"'
binaries = ["wesnoth", "wesnoth_editor"]
for bin in binaries:
    #icon = env.Command(bin + "-icon.ico", join("../../icons", bin + "-icon.png"), "$IM_CONVERT $SOURCE $TARGET")
    try:
        res = [env.RES(bin + ".rc")]
        #env.Depends(res, icon)
    except AttributeError:
        res = []
    locals()[bin + "_res"] = res
    Export(bin + "_res")
