FROM rwgrim/msys2-cross
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y scons g++-mingw-w64-x86-64 pkg-config python3-pefile expect && \
    update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists

RUN pacman-cross -S --noconfirm \
    mingw-w64-x86_64-boost \
    mingw-w64-x86_64-SDL2 \
    mingw-w64-x86_64-SDL2_image \
    mingw-w64-x86_64-SDL2_mixer \
    mingw-w64-x86_64-SDL2_ttf \
    mingw-w64-x86_64-pango
