FROM wesnoth/wesnoth:1804-master

# install ppa for more recent flatpak version, otherwise "dir" source type is unrecognized
RUN apt install -y software-properties-common
RUN add-apt-repository -y ppa:alexlarsson/flatpak
RUN apt update
# install flatpak
RUN apt install -y flatpak flatpak-builder jq
RUN flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
# install runtime
RUN flatpak install -y flathub org.freedesktop.Platform/x86_64/19.08 org.freedesktop.Sdk/x86_64/19.08
