name: Bug Report
description: Create a bug report to help us improve the game.
labels: ['Bug']

body:
  - type: textarea
    id: info
    attributes:
      label: Game and System Information
      description: |
        - What version of the game are you running? (If you built wesnoth yourself, mention the exact commit)
        - What OS are you running?
      value: |
        - **Version:**
        - **OS:**

  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: to_reproduce
    attributes:
      label: Steps to reproduce the behavior
      placeholder: |
        1.
        2.
        3.

  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen. If applicable, add screenshots or savefiles to help explain your problem.
        To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.

  - type: textarea
    id: more_info
    attributes:
      label: Additional context
      description: Add any other context (compiler logs, console output, etc) about the problem here.
