FROM ubuntu:16.04

RUN apt update

RUN apt install -y -qq apt-utils

# boost
RUN apt install -y -qq libboost-filesystem1.58-dev libboost-filesystem1.58.0 libboost-iostreams1.58-dev libboost-iostreams1.58.0 libboost-locale1.58-dev libboost-locale1.58.0 libboost-regex1.58-dev libboost-regex1.58.0 libboost-serialization1.58-dev libboost-serialization1.58.0 libasio-dev libboost-program-options1.58-dev libboost-program-options1.58.0 libboost-random1.58-dev libboost-random1.58.0 libboost-system1.58-dev libboost-system1.58.0 libboost-thread1.58-dev libboost-thread1.58.0 libboost-test-dev

# SDL
RUN apt install -y -qq libsdl2-2.0-0 libsdl2-dev libsdl2-image-2.0-0 libsdl2-image-dev libsdl2-mixer-2.0-0 libsdl2-mixer-dev libsdl2-ttf-2.0-0 libsdl2-ttf-dev

# misc
RUN apt install -y -qq libpng12-0 libpng12-dev libreadline6-dev libvorbis-dev libcairo2 libcairo2-dev libpango-1.0-0 libpango1.0-dev libfribidi0 libfribidi-dev libbz2-1.0 libbz2-dev zlib1g zlib1g-dev libpangocairo-1.0-0 libssl-dev

# programs
RUN apt install -y -qq openssl gdb xvfb bzip2 git scons cmake make ccache gcc g++ clang

WORKDIR /home/wesnoth-travis

