Import("env")

env.ScanReplace("wesnothd.service", "wesnothd.service.scons.in")
env.ScanReplace("wesnothd.tmpfiles.conf", "wesnothd.tmpfiles.conf.in")
env.ScanReplace("wesnothd.sysusers.conf", "wesnothd.sysusers.conf.in")
