.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"

.TH WESNOTHD 6 "April 9th 2005" "Wesnothd" "Battle for Wesnoth multiplayer network daemon"

.SH NAME
battle for wesnoth multiplayer network daemon

.SH SYNOPSIS
.B wesnothd

.SH DESCRIPTION
Battle for
.B Wesnoth
multiplayer network daemon

.SH OPTIONS

.TP
.BR -d , \ --daemon
runs wesnothd as a daemon.

.TP
.BR --fifo PATH
sets PATH of file to be used for input stream.

.TP
.BR -h , \ --help
tells you what the command line options do.

.TP
.BR -m , \ --max_packet_size
sets maximum packet size to the specified value.

.TP
.BR -p , \ --port
binds the server to the specified port. If no port is specified, port 15000 will be used.

.TP
.BR -v , \ --version
shows version number and exits.

.SH AUTHOR
Written by David White <davidnwhite@optusnet.com.au>.
Edited by Nils Kneuper <crazy-ivanovic@gmx.net>.
This manual page was originally written by Cyril Bouthors <cyril@bouthors.org>.
.br
Visit the official homepage: http://www.wesnoth.org/

.SH COPYRIGHT
Copyright \(co 2003 David White <davidnwhite@optusnet.com.au>
.br
This is Free Software; this software is licensed under the GPL version 2, as published by the Free Software Foundation.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
