.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"

.TH WESNOTH_EDITOR 6 "January 22nd, 2004" "Wesnoth_editor" "Battle for Wesnoth map editor"

.SH NAME
battle for wesnoth map editor

.SH SYNOPSIS
.B wesnoth_editor

.SH DESCRIPTION
Battle for
.B Wesnoth
map editor

.SH OPTIONS

.TP
.BR --datadir
selects the data directory to use.

.TP
.BR -f , \ --fullscreen
runs the game in full screen mode.

.TP
.BR -h , \ --help
tells you about what the command line options do.

.TP
.BR --path
prints the name of the game data directory and exits.

.TP
.BR -r , \ --resolution
sets screen resolution. Example: -r 800x600

.TP
.BR -v , \ --version
prints version number and exit.

.TP
.BR -w , \ --windowed
runs the game in windowed mode.

.SH AUTHOR
Written by David White <davidnwhite@optusnet.com.au>.
Edited by Nils Kneuper <crazy-ivanovic@gmx.net>.
This manual page was originally written by Cyril Bouthors <cyril@bouthors.org>.
.br
Visit the official homepage: http://www.wesnoth.org/

.SH COPYRIGHT
Copyright \(co 2003 David White <davidnwhite@optusnet.com.au>
.br
This is Free Software; this software is licensed under the GPL version 2, as published by the Free Software Foundation.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
