#!/bin/bash
if [ "$1" == "-n" ]; then
	echo=echo
	shift
else
	echo=""
fi
if ! [ $# -ge 1 ]; then
        echo "Syntax: $0 [-n] <new minor version>"
        exit 1
fi
[ $1 -ge 1 ] || exit 1
#if ! ps -C wesnothd-1.3-prev>/dev/null; then
#	echo "Previous server isn't running!"
#	exit 1
#fi
$echo sed -i -e "s/\(versions_accepted=.*\)1\.3\.$(($1-2))/\11.3.$(($1-1))/g" ~/servers/1.3-prev/wesnothd.cfg
$echo sed -i -e "s/motd=\(.*\)1\.3\.$(($1-1))/motd=\11.3.$1/g" ~/servers/1.3-prev/wesnothd.cfg
# reload the config
$echo killall -SIGHUP wesnothd-1.3-prev || exit 1
$echo sed -i -e "s/\(versions_accepted=.*\)1\.3\.$(($1-1))/\11.3.$(($1+1))/g" ~/servers/1.3/wesnothd.cfg
$echo sed -i -e "s/motd=\(.*\)1\.3\.$(($1-1))/motd=\11.3.$1/g" ~/servers/1.3/wesnothd.cfg
# update previous version redirect
$echo sed -i -e "/\[redirect\]/N;s/\(version=.*\)1\.3\.$(($1-2))/\11.3.$(($1-1))/g" ~/servers/1.3/wesnothd.cfg
# reload the config
$echo killall -SIGHUP wesnothd-1.3 || exit 1
$echo send_server_command 1.3 msg Version 1.3.$1 released! New users with the previous version will be redirected to a temporary server that will run until binaries for all major OSs are out.
