.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"

.TH WESNOTH 6 "Juni 2005" "wesnoth" "Battle for Wesnoth"

.SH NAME
Battle for Wesnoth \- rundebasiertes Strategiespiel

.SH ZUSAMMENFASSUNG
.B wesnoth
[\fIOPTIONEN\fR]
[\fIORT DER SPIELDATEN\fR]

.SH BESCHREIBUNG
Battle for
.B Wesnoth
ist ein rundenbasiertes Strategiespiel in einem Fantasy Szeanrio.

Schlüpft in die Rolle eines Herrführers und führt Eure Armee zum Sieg. Wählt aus verschiedenen Rassen, mit unterschiedlichen Fertigkeiten, Waffen und Sprüchen aus und zerschmettert Euren Gegner.

.SH KOMMANDOZEILENOPTIONEN

.TP
.B --bpp
Bestimmt die Farbtiefe, in der das Spiel gestartet wird. Bsp: --bpp32

.TP
.B --compress \ <entpackte_datei> \ <komprimierte_datei>
Wandelt eine normale WML-Textdatei (entpackte_datei) in einen als WML-Binärdatei komprimierten Spielstand (komprimierte_datei) um.

.TP
.BR -d , \ --debug
Zeigt Eintwicklerinformationen im Spiel an.

.TP
.B --decompress \ <komprimierte_datei> \ <entpackte_datei>
Wandelt einen als WML-Binärdatei komprimierten Spielstand (komprimierte_datei) in eine normale WML-Textdatei (entpackte_datei) um.

.TP
.BR -f , \ --fullscreen
Startet das Programm im Vollbildmodus.

.TP
.B --fps
Aktiviert die Anzeige der Bilder pro Sekunde im Spiel.

.TP
.BR -h , \ --help
Gibt die möglichen Kommandozeilenoptionen aus.

.TP
.BR --log-error="domain1,domain2,..." , \ --log-warning=... , \ --log-info=...
Setzt die Stufe der Debugausgabe. Verwenden Sie "all", um sämtliche Meldungen auszugeben.
.B --log-info
zeigt alle Meldungen,
.B --log-warning
zeigt nur Warnungen und Fehler und
.B --log-error
nur Fehler.


.TP
.B --multiplayer
Starte das Spiel im Mehrerspieler-Modus. Es gibt noch zusätzliche Optionen die zusammen mit
.B --multiplayer
 verwendet werden können. Diese werden weiter unten näher erklärt.

.TP
.BR --nocache
Veranlasst das Programm, keine Daten zwischen zu speichern.

.TP
.BR --nosound
Deaktiviert jegliche Soundeffekte im Spiel.

.TP
.BR --path
Zeigt an, wo sich der Ordner mit den Spieldateien befindet .

.TP
.BR -r , \ --resolution
Ermöglicht es, die Auflösung zu bestimmen, in der das Spiel gestartet wird. Bsp: -r 800x600

.TP
.BR -t , \ --test
Startet das Programm mit einem kleinen Testszenario.

.TP
.BR -v , \ --version
Zeigt die Versionsnummer an und beendet das Programm.

.TP
.BR -w , \ --windowed
Startet das Programm im Fenstermodus.

.SH Zusätzliche Optionen für --multiplayer

Die seitenspezifischen Einstellungen sind mit <NUMMER> markiert. <NUMMER> muss dabei durch die Nummer der jeweiligen Seite ersetzt werden. Meistens ist diese Nummer 1 oder 2, doch hängt es letztendlich von der Anzahl der möglichen Spieler in dem gewählten Scenario ab.

.TP
.BR --era=<WERT>
Bestimmt, welche Ära für diese Partie genutzt werden soll. Die Ära wird per "id" bestimmt. Eine genaue Beschreibung der Rassen und Epochen ist in der Datei data/multiplayer.cfg zu finden.

.TP
.BR --nogui
Das Spiel startet ohne grafische Oberfläche.

.TP
.BR --scenario=<WERT>
Bestimmt das Szenario, dass geladen werden soll. Standard ist "multiplayer_test".

.TP
.BR --algorithm<NUMMER>=<WERT>
Legt einen anderen als den Standardalgorithmus für die KI der gewählten Seite fest. Mögliche Werte sind "idle_ai" oder "sample_ai".

.TP
.BR --controller<NUMMER>=<WERT>
Bestimmt, wer die gewählte Seite kontrolliert. Mögliche Werte sind "human" für einen Menschen oder "ai" für einen KI-Spieler.

.TP
.BR --parm<NUMMER>=<NAME>:<WERT>
Gibt zusätzliche Parameter fr diese Seite an. Die möglichen Parameter hängen davon ab, welche Optionen für
.B --controller
und
.B --algorithm
verwendet werden. Diese Einstellung ist nur interessant, wenn Sie Ihre eigene "KI" entwickeln wollen.

.TP
.BR --side<NUMMER>=<WERT>
Bestimmt die Rasse für die festegelegte Seite in Abhängigkeit von der gewählten Ära. Die Rasse wird per "id" bestimmt. Eine genaue Beschreibung der Rassen und Epochen ist in der Datei data/multiplayer.cfg zu finden.

.SH AUTOR
Geschrieben von David White <davidnwhite@comcast.net>.
Bearbeitet von Nils Kneuper <crazy-ivanovic@gmx.net> und ott <ott@gaon.net>.
Übersetzt von Jan-Heiner Laberenz <Jan-Heiner@arcor.de> und Nils Kneuper <crazy-ivanovic@gmx.net>.
Diese Beschreibung stammt im Original von Cyril Bouthors <cyril@bouthors.org>.
.br
Besucht auch die offizielle Internetseite: http://www.wesnoth.org/

.SH COPYRIGHT
Copyright \(co 2003 David White <davidnwhite@comcast.net>
.br
Dieses Programm ist freie Software. Sie können es unter den Bedingungen der GNU General Public License, wie von der Free Software Foundation veröffentlicht, weitergeben und/oder modifizieren, entweder gemäß Version 2 der Lizenz oder (nach Ihrer Option) jeder späteren Version.
.br
Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, dass es Ihnen von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. Details finden Sie in der GNU General Public License.
.br
Sie sollten eine Kopie der GNU General Public License zusammen mit diesem Programm erhalten haben. Falls nicht, schreiben Sie an die Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

.SH ANDERE
wesnothd(6), wesnoth_editor(6)