FROM ubuntu:24.04

RUN apt update

RUN apt install -y -qq apt-utils

# make tzdata not prompt for a timezone
ENV DEBIAN_FRONTEND=noninteractive

# translations
RUN apt install -y -qq asciidoc dos2unix xsltproc po4a docbook-xsl language-pack-en
RUN locale-gen en_US.UTF-8

# programs
RUN apt install -y -qq openssl gdb xvfb bzip2 git scons cmake make ccache gcc g++ clang clang-tidy lld doxygen graphviz lua-check curl meson gperf

# android stuff
WORKDIR /home/wesnoth-android/.android/sdk

RUN apt install -y -qq meson gperf openjdk-17-jdk-headless wget autoconf pkg-config
RUN wget -nc "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip" -P .
RUN unzip ./commandlinetools-linux-11076708_latest.zip -d .
RUN mkdir cmdline-tools/latest
RUN mv ./cmdline-tools/bin cmdline-tools/latest/bin
RUN mv ./cmdline-tools/lib cmdline-tools/latest/lib

RUN yes | ./cmdline-tools/latest/bin/sdkmanager "tools" "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;26.3.11579264"

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV ANDROID_HOME=/home/wesnoth-android/.android/sdk
ENV ANDROID_SDK_ROOT=/home/wesnoth-android/.android/sdk
ENV ANDROID_NDK_ROOT=/home/wesnoth-android/.android/sdk/ndk/26.3.11579264
