#!/bin/sh
set -e

# copy relevant messages from SRCDOMAIN to DSTDOMAIN, for LANG

SRCDOMAIN=$1
DSTDOMAIN=$2
LANG=$3

# merge the 2 files
msgcat --use-first -F po/$DSTDOMAIN/$LANG.po po/$SRCDOMAIN/$LANG.po >tmp
mv po/$DSTDOMAIN/$LANG.po po/$DSTDOMAIN/$LANG.po.bak
mv tmp po/$DSTDOMAIN/$LANG.po

# sync with DST pot
make -C po DOMAIN=$DSTDOMAIN $LANG.po

# clear those obsolete strings added by SRC, but keep ours if any
msgattrib --no-obsolete po/$DSTDOMAIN/$LANG.po >tmp
msgcat --use-first -F tmp po/$DSTDOMAIN/$LANG.po.bak > po/$DSTDOMAIN/$LANG.po

rm po/stamp-po 
make -C po
