# vi: syntax=python
import glob

sources = glob.glob("src/*.cpp") + glob.glob("src/widgets/*.cpp") +\
     glob.glob("src/serialization/*.cpp") +  glob.glob("src/sdl_ttf/*.c")
sources.remove("src/loadscreen_empty.cpp")

env = Environment()

# The cross compiler to use
env["CC"] = "i586-mingw32msvc-gcc"
env["CXX"] = "i586-mingw32msvc-g++"

# Dependencies: SDL, SDL_net, SDL_mixer, SDL_image, freetype, libintl
# This is where I put the dependency headers
env.Append(CPPPATH = ["../win-deps/include"])

# This is where I put the dependency libs
env.Append(LIBPATH = ["../win-deps/lib"])

# Compilation settings
env.Append(CCFLAGS = ["-O2", "-mthreads"])
env.Append(LINKFLAGS = ["-s", "-mwindows", "-lmingwthrd"])
env.Append(CPPPATH = ["src", "src/widgets"])
env.Append(LIBS = ["mingw32", "SDLmain", "SDL", "SDL_net", "SDL_mixer", "SDL_image",
     "intl", "wsock32", "freetype"])

# Scons stuff
env.BuildDir("../build", "src")
env.SConsignFile("sconsign")

# Windows stuff
env["PROGSUFFIX"] = ".exe"

# Compile it!
env.Program("wesnoth", ["../build/" + x[4:] for x in sources])

