#!/bin/sh -xe

cd steamrt
docker build -t steamos-wesnoth .
rm -rf ../steambuild
mkdir ../steambuild
if [ -d "$PWD"/../../../build ]; then
    echo "Existing scons 'build' directory found, this may cause the build to fail!"
fi
docker run -v "$PWD"/../../..:/wesnoth -v "$PWD"/../steambuild:/output --tmpfs /build:exec -u "$UID" steamos-wesnoth
