#!/bin/sh

set -xeu

VALVEFILE=com.valvesoftware.SteamRuntime.Sdk-amd64,i386-sniper-sysroot.Dockerfile
VALVETAR=com.valvesoftware.SteamRuntime.Sdk-amd64,i386-sniper-sysroot.tar.gz
VALVE_SNAPSHOT=0.20240415.84603

DOCKERBASEIMAGE=steamrt_sniper_amd64
DOCKERLOCALIMAGE=wesnoth/wesnoth:steamrt-sniper
DOCKERLOCALFILE=./CI/Dockerfile-base-steamrt

if [ ! -f "$VALVEFILE" ]; then
    wget https://repo.steampowered.com/steamrt-images-sniper/snapshots/"$VALVE_SNAPSHOT"/"$VALVEFILE"
fi
if [ ! -f "$VALVETAR" ]; then
    wget https://repo.steampowered.com/steamrt-images-sniper/snapshots/"$VALVE_SNAPSHOT"/"$VALVETAR"
fi

docker build -t "$DOCKERBASEIMAGE" -f "$VALVEFILE" .

docker build -t "$DOCKERLOCALIMAGE" -f "$DOCKERLOCALFILE" .
