#!/bin/sh -xe

cd mingw
docker build -t mingw-wesnoth .
rm -rf ../mingwbuild
mkdir ../mingwbuild
docker run -v "$PWD"/../../..:/wesnoth -v "$PWD"/../mingwbuild:/output --tmpfs /build -u "$UID" mingw-wesnoth
