# vi: syntax=python:et:ts=4

Import("env")

ana = env.Library("ana", Split("""
    asio_listener.cpp
    asio_sender.cpp
    asio_server.cpp
    asio_client.cpp
    asio_proxy_connection.cpp
    asio_timers.cpp
    """))
Return("ana")
