#ifndef WIDGET_DEFINES_HPP_INCLUDED
#define WIDGET_DEFINES_HPP_INCLUDED

char const HELP_STRING_SEPARATOR = '|', DEFAULT_ITEM = '*', COLUMN_SEPARATOR = '=',
           IMAGE_PREFIX = '&', IMG_TEXT_SEPARATOR = 1;

#endif
