/*
* generated by Xtext
*/
package org.wesnoth.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.wesnoth.services.WMLGrammarAccess;

public class WMLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private WMLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_EOL", "RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.wesnoth.parser.antlr.internal.InternalWMLParser createParser(XtextTokenStream stream) {
		return new org.wesnoth.parser.antlr.internal.InternalWMLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "WMLRoot";
	}
	
	public WMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(WMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
