#!/usr/bin/env python
#
import sys

for filename in sys.argv[1:]:
    contents = open(filename).read().split("\n")
    while "," not in contents[0]:
        contents.pop(0)
    width = contents[0].count(",")
    if not contents[0].strip().endswith(","):
        width += 1
    height = len(filter(lambda x: "," in x, contents))
    print "***", filename, width, height, width/5, height/5
