name: Greetings

on: [pull_request] # Add issues if we want a message there too

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users'' first issue"
        pr-message: "Hi! :D Since this is your first pull request, don't forget to add yourself to the [credits](https://github.com/wesnoth/wesnoth/blob/master/data/core/about.cfg) under Miscellaneous Contributors."
