name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi! Thanks for helping make Wesnoth even better!"
        pr-message: "Hi! :D Since this is your first pull request, don't forget to add yourself to the [credits](https://github.com/wesnoth/wesnoth/blob/master/data/core/about.cfg) under Miscellaneous Contributors."
